kumuluzee:
  name: pretvornik-protokolov
  server:
    http:
      port: 9094
  version: 1.0
  env:
    name: dev
  cors-filter:
    servlet:
      enabled: true
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, HEAD, OPTIONS, DELETE"